/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.ejemplocarrito.views;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class BuscarProductoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarProductoView
     */
    public BuscarProductoView() {
        initComponents();
    }

    public JButton getBttBuscar() {
        return BttBuscar;
    }

    public void setBttBuscar(JButton BttBuscar) {
        this.BttBuscar = BttBuscar;
    }

    public JButton getBttCancelar() {
        return BttCancelar;
    }

    public void setBttCancelar(JButton BttCancelar) {
        this.BttCancelar = BttCancelar;
    }

    public JTextField getTxtBuscarProducto() {
        return TxtBuscarProducto;
    }

    public void setTxtBuscarProducto(JTextField TxtBuscarProducto) {
        this.TxtBuscarProducto = TxtBuscarProducto;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelPregunta = new javax.swing.JLabel();
        TxtBuscarProducto = new javax.swing.JTextField();
        BttBuscar = new javax.swing.JButton();
        BttCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Buscar Producto");

        jLabelPregunta.setText("Que producto desea Buscar?");

        TxtBuscarProducto.setText("Buscar...");

        BttBuscar.setText("Buscar");

        BttCancelar.setText("Cancelar");
        BttCancelar.addActionListener(this::BttCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabelPregunta))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(BttBuscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BttCancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(TxtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPregunta)
                .addGap(18, 18, 18)
                .addComponent(TxtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BttBuscar)
                    .addComponent(BttCancelar))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BttCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BttCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttBuscar;
    private javax.swing.JButton BttCancelar;
    private javax.swing.JTextField TxtBuscarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPregunta;
    // End of variables declaration//GEN-END:variables
}
