/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.ejemplocarrito.views;
import ec.edu.ups.carrito.dao.ProductoDAOMemoria;
import ec.edu.ups.ejemplocarrito.controllers.ProductoController;
import java.util.Locale;
import java.util.ResourceBundle;


/**
 *
 * @author USER
 */
public class PrincipalView extends javax.swing.JFrame {
    private CrearProductoView crearProductoView;
    private BuscarProductoView buscarProductoView;
    private ActualizarProductoView actualizarProductoView;
    private EliminarProductoView eliminarProductoView;
    private ListarProductosView listarProductosView;
    private ProductoController productoController;
    private ProductoDAOMemoria productoDAO;

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
        crearProductoView = new CrearProductoView();
        productoDAO = new ProductoDAOMemoria();
        buscarProductoView = new BuscarProductoView();
        actualizarProductoView = new ActualizarProductoView();
        eliminarProductoView = new EliminarProductoView();
        listarProductosView = new ListarProductosView();
        productoController = new ProductoController(productoDAO,crearProductoView,buscarProductoView,actualizarProductoView,eliminarProductoView,listarProductosView);
    }
    public void cambiarIdioma(Locale locale){
        ResourceBundle Bundle = ResourceBundle.getBundle("ec.edu.ups.ejemplocarrito.i18n.mensajes", locale);
        productosMenu.setText(Bundle.getString("ProductoMenu"));
        crearProductoMenuItem.setText(Bundle.getString("crearMenuItem"));
        buscarProductoMenuItem.setText(Bundle.getString("buscarMenuItem"));
        eliminarProductoMenuItem.setText(Bundle.getString("eliminarMenuItem"));
        actualizarProductoMenuItem.setText("actualizarMenuItem");
        listarProductoMenuItem.setText("listarMenuItem");
        // OTRO MENU
        CarritoMenu.setText(Bundle.getString("carritoMenu"));
        agregarItemProductoMenuItem.setText(Bundle.getString("agregarMenuItem"));
        eliminarItemProductoMenuItem.setText(Bundle.getString("eliminarMenuItem"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        ProductoMenu = new javax.swing.JMenuBar();
        productosMenu = new javax.swing.JMenu();
        crearProductoMenuItem = new javax.swing.JMenuItem();
        buscarProductoMenuItem = new javax.swing.JMenuItem();
        eliminarProductoMenuItem = new javax.swing.JMenuItem();
        actualizarProductoMenuItem = new javax.swing.JMenuItem();
        listarProductoMenuItem = new javax.swing.JMenuItem();
        CarritoMenu = new javax.swing.JMenu();
        agregarItemProductoMenuItem = new javax.swing.JMenuItem();
        eliminarItemProductoMenuItem = new javax.swing.JMenuItem();
        IdiomaMenu = new javax.swing.JMenu();
        idiomaEspaniolMenuItem = new javax.swing.JMenuItem();
        idiomaEnglishlMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productosMenu.setMnemonic('f');
        productosMenu.setText("Productos");

        crearProductoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        crearProductoMenuItem.setMnemonic('o');
        crearProductoMenuItem.setText("Crear");
        crearProductoMenuItem.addActionListener(this::crearProductoMenuItemActionPerformed);
        productosMenu.add(crearProductoMenuItem);

        buscarProductoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        buscarProductoMenuItem.setMnemonic('s');
        buscarProductoMenuItem.setText("Buscar");
        buscarProductoMenuItem.setToolTipText("");
        buscarProductoMenuItem.addActionListener(this::buscarProductoMenuItemActionPerformed);
        productosMenu.add(buscarProductoMenuItem);

        eliminarProductoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        eliminarProductoMenuItem.setMnemonic('a');
        eliminarProductoMenuItem.setText("Eliminar");
        eliminarProductoMenuItem.addActionListener(this::eliminarProductoMenuItemActionPerformed);
        productosMenu.add(eliminarProductoMenuItem);

        actualizarProductoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        actualizarProductoMenuItem.setMnemonic('x');
        actualizarProductoMenuItem.setText("Actualizar");
        actualizarProductoMenuItem.addActionListener(this::actualizarProductoMenuItemActionPerformed);
        productosMenu.add(actualizarProductoMenuItem);

        listarProductoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        listarProductoMenuItem.setText("ListarProducto");
        listarProductoMenuItem.addActionListener(this::listarProductoMenuItemActionPerformed);
        productosMenu.add(listarProductoMenuItem);

        ProductoMenu.add(productosMenu);

        CarritoMenu.setMnemonic('e');
        CarritoMenu.setText("Carrito");

        agregarItemProductoMenuItem.setMnemonic('t');
        agregarItemProductoMenuItem.setText("Agregar");
        CarritoMenu.add(agregarItemProductoMenuItem);

        eliminarItemProductoMenuItem.setMnemonic('y');
        eliminarItemProductoMenuItem.setText("Eliminar");
        CarritoMenu.add(eliminarItemProductoMenuItem);

        ProductoMenu.add(CarritoMenu);

        IdiomaMenu.setText("Idioma");

        idiomaEspaniolMenuItem.setText("Español");
        idiomaEspaniolMenuItem.addActionListener(this::idiomaEspaniolMenuItemActionPerformed);
        IdiomaMenu.add(idiomaEspaniolMenuItem);

        idiomaEnglishlMenuItem.setText("Ingles");
        idiomaEnglishlMenuItem.addActionListener(this::idiomaEnglishlMenuItemActionPerformed);
        IdiomaMenu.add(idiomaEnglishlMenuItem);

        ProductoMenu.add(IdiomaMenu);

        setJMenuBar(ProductoMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProductoMenuItemActionPerformed
       if( !actualizarProductoView.isVisible()){
           desktopPane.remove(actualizarProductoView);
           actualizarProductoView.setVisible(true);
           desktopPane.add(actualizarProductoView);
       }
    }//GEN-LAST:event_actualizarProductoMenuItemActionPerformed

    private void crearProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductoMenuItemActionPerformed
        // TODO add your handling code here:
        if(!crearProductoView.isVisible()){ 
           desktopPane.remove(crearProductoView);
           crearProductoView.setVisible(true);
           desktopPane.add(crearProductoView);            
        }
    }//GEN-LAST:event_crearProductoMenuItemActionPerformed

    private void buscarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoMenuItemActionPerformed
        // TODO add your handling code here:
        if( !buscarProductoView.isVisible()){
            desktopPane.remove(buscarProductoView);
            buscarProductoView.setVisible(true);
            desktopPane.add(buscarProductoView);
        }
    }//GEN-LAST:event_buscarProductoMenuItemActionPerformed

    private void eliminarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoMenuItemActionPerformed
        // TODO add your handling code here:
        if(!eliminarProductoView.isVisible()){
            desktopPane.remove(eliminarProductoView);
            eliminarProductoView.setVisible(true);
            desktopPane.add(eliminarProductoView);
        }
    }//GEN-LAST:event_eliminarProductoMenuItemActionPerformed

    private void listarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProductoMenuItemActionPerformed
        // TODO add your handling code here:
        if(!listarProductosView.isVisible()){
            desktopPane.remove(listarProductosView);
            listarProductosView.setVisible(true);
            desktopPane.add(listarProductosView);
            
        }
    }//GEN-LAST:event_listarProductoMenuItemActionPerformed

    private void idiomaEspaniolMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomaEspaniolMenuItemActionPerformed
        // TODO add your handling code here:
        Locale locale = new Locale("es","EC");
        cambiarIdioma(locale);
    }//GEN-LAST:event_idiomaEspaniolMenuItemActionPerformed

    private void idiomaEnglishlMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomaEnglishlMenuItemActionPerformed
        // TODO add your handling code here:
        Locale locale = new Locale("en","US");
        cambiarIdioma(locale);
    }//GEN-LAST:event_idiomaEnglishlMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CarritoMenu;
    private javax.swing.JMenu IdiomaMenu;
    private javax.swing.JMenuBar ProductoMenu;
    private javax.swing.JMenuItem actualizarProductoMenuItem;
    private javax.swing.JMenuItem agregarItemProductoMenuItem;
    private javax.swing.JMenuItem buscarProductoMenuItem;
    private javax.swing.JMenuItem crearProductoMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem eliminarItemProductoMenuItem;
    private javax.swing.JMenuItem eliminarProductoMenuItem;
    private javax.swing.JMenuItem idiomaEnglishlMenuItem;
    private javax.swing.JMenuItem idiomaEspaniolMenuItem;
    private javax.swing.JMenuItem listarProductoMenuItem;
    private javax.swing.JMenu productosMenu;
    // End of variables declaration//GEN-END:variables

}
