/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.ejemplocarrito.views;

/**
 *
 * @author USER
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        ProductoMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        crearProductoMenuItem = new javax.swing.JMenuItem();
        buscarProductoMenuItem = new javax.swing.JMenuItem();
        eliminarProductoMenuItem = new javax.swing.JMenuItem();
        actualizarProductoMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        agregarItemProductoMenuItem = new javax.swing.JMenuItem();
        eliminarItemProductoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Productos");

        crearProductoMenuItem.setMnemonic('o');
        crearProductoMenuItem.setText("Crear");
        crearProductoMenuItem.addActionListener(this::crearProductoMenuItemActionPerformed);
        fileMenu.add(crearProductoMenuItem);

        buscarProductoMenuItem.setMnemonic('s');
        buscarProductoMenuItem.setText("Buscar");
        buscarProductoMenuItem.setToolTipText("");
        fileMenu.add(buscarProductoMenuItem);

        eliminarProductoMenuItem.setMnemonic('a');
        eliminarProductoMenuItem.setText("Eliminar");
        fileMenu.add(eliminarProductoMenuItem);

        actualizarProductoMenuItem.setMnemonic('x');
        actualizarProductoMenuItem.setText("Actualizar");
        actualizarProductoMenuItem.addActionListener(this::actualizarProductoMenuItemActionPerformed);
        fileMenu.add(actualizarProductoMenuItem);

        ProductoMenu.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Carrito");

        agregarItemProductoMenuItem.setMnemonic('t');
        agregarItemProductoMenuItem.setText("Agregar");
        editMenu.add(agregarItemProductoMenuItem);

        eliminarItemProductoMenuItem.setMnemonic('y');
        eliminarItemProductoMenuItem.setText("Eliminar");
        editMenu.add(eliminarItemProductoMenuItem);

        ProductoMenu.add(editMenu);

        setJMenuBar(ProductoMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProductoMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_actualizarProductoMenuItemActionPerformed

    private void crearProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProductoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearProductoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar ProductoMenu;
    private javax.swing.JMenuItem actualizarProductoMenuItem;
    private javax.swing.JMenuItem agregarItemProductoMenuItem;
    private javax.swing.JMenuItem buscarProductoMenuItem;
    private javax.swing.JMenuItem crearProductoMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem eliminarItemProductoMenuItem;
    private javax.swing.JMenuItem eliminarProductoMenuItem;
    private javax.swing.JMenu fileMenu;
    // End of variables declaration//GEN-END:variables

}
